FROM node:18-slim AS build

ENV NODE_ENV development

WORKDIR /app

COPY package.json package.json

RUN yarn

COPY public public
COPY config-overrides.js config-overrides.js
COPY src src

RUN yarn build

FROM nginx:stable-alpine

COPY --from=build /app/build /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]

EXPOSE 80
